spring:
  application:
    name: poortravel-service-upload
  boot:
    admin:
      client:
        url: http://localhost:8084
        instance:
          service-url: http://localhost:8505
          name: poortravel-service-upload
fastdfs.base.url: http://localhost:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: localhost:22122

server:
  port: 8505
