version: '3.1'
services:
  poortravel-zipkin:
    restart: always
    image: 47.101.152.189:5000/poortravel-zipkin
    container_name: poortravel-zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin_network
networks:
  zipkin_network: