stages:
  - build
  - push
  - run
  - clean

build:
  stage: build
  script:
    - /usr/local/maven/apache-maven-3.6.1/bin/mvn clean package
    - cp target/poortravel-service-admin-1.0.0-SNAPSHOT.jar docker
    - cd docker
    - docker build -t 47.101.152.189:5000/poortravel-service-admin .

push:
  stage: push
  script:
    - docker push 47.101.152.189:5000/poortravel-service-admin

run:
  stage: run
  script:
    - cd docker
    - docker-compose down
    - docker-compose up -d

clean:
  stage: clean
  script:
    - docker rmi $(docker images -q -f dangling=true)